# Default values for annif-utils

# images
apiImage: quay.io/natlibfi/annif:latest

# To avoid remote pulling with local kubernetes, you can set this to 'IfNotPresent'
apiImagePullPolicy: Always

# Replica counts for api and worker
apiReplicas: 1

# Ingress type can be 'Ingress' for K8s ingresses or 'Route' for OpenShift Routes
ingressType: Ingress

# Ingress host
ingressHost: localhost

# ----------------------------------------------------------------------------
# Application content

projectsTarballUrl: << url to the tar package >>
