{{- if eq .Values.ingressType "Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: annif
  labels:
    app: annif
spec:
  {{- if .Values.ingressHost }}
  host: {{ .Values.ingressHost }}
  {{- end }}
  to:
    kind: Service
    name: api
    weight: 100
  port:
    targetPort: annif
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress: []
{{- end}}
