apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the API pods
  name: api
  labels:
    app: annif
spec:
  ports:
    - name: annif
      port: 5000
      targetPort: 5000
    - name: mauiserver
      port: 8080
      targetPort: 8080
  selector:
    name: api
