apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the API pods
  name: api
  labels:
    app: annif
spec:
  ports:
    - name: api
      port: 5000
      targetPort: 5000
  selector:
    name: api
